package com.lqs.sms.mapper;

import com.lqs.sms.entity.LibraryView;
import com.lqs.sms.entity.LibraryViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LibraryViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_view
     *
     * @mbg.generated Fri Mar 05 16:41:07 CST 2021
     */
    long countByExample(LibraryViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_view
     *
     * @mbg.generated Fri Mar 05 16:41:07 CST 2021
     */
    int deleteByExample(LibraryViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_view
     *
     * @mbg.generated Fri Mar 05 16:41:07 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_view
     *
     * @mbg.generated Fri Mar 05 16:41:07 CST 2021
     */
    int insert(LibraryView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_view
     *
     * @mbg.generated Fri Mar 05 16:41:07 CST 2021
     */
    int insertSelective(LibraryView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_view
     *
     * @mbg.generated Fri Mar 05 16:41:07 CST 2021
     */
    List<LibraryView> selectByExample(LibraryViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_view
     *
     * @mbg.generated Fri Mar 05 16:41:07 CST 2021
     */
    LibraryView selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_view
     *
     * @mbg.generated Fri Mar 05 16:41:07 CST 2021
     */
    int updateByExampleSelective(@Param("record") LibraryView record, @Param("example") LibraryViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_view
     *
     * @mbg.generated Fri Mar 05 16:41:07 CST 2021
     */
    int updateByExample(@Param("record") LibraryView record, @Param("example") LibraryViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_view
     *
     * @mbg.generated Fri Mar 05 16:41:07 CST 2021
     */
    int updateByPrimaryKeySelective(LibraryView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_view
     *
     * @mbg.generated Fri Mar 05 16:41:07 CST 2021
     */
    int updateByPrimaryKey(LibraryView record);
}