package com.lqs.sms.mapper;

import com.lqs.sms.entity.LibraryType;
import com.lqs.sms.entity.LibraryTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LibraryTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_type
     *
     * @mbg.generated Fri Mar 05 16:40:49 CST 2021
     */
    long countByExample(LibraryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_type
     *
     * @mbg.generated Fri Mar 05 16:40:49 CST 2021
     */
    int deleteByExample(LibraryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_type
     *
     * @mbg.generated Fri Mar 05 16:40:49 CST 2021
     */
    int deleteByPrimaryKey(Integer libtypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_type
     *
     * @mbg.generated Fri Mar 05 16:40:49 CST 2021
     */
    int insert(LibraryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_type
     *
     * @mbg.generated Fri Mar 05 16:40:49 CST 2021
     */
    int insertSelective(LibraryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_type
     *
     * @mbg.generated Fri Mar 05 16:40:49 CST 2021
     */
    List<LibraryType> selectByExample(LibraryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_type
     *
     * @mbg.generated Fri Mar 05 16:40:49 CST 2021
     */
    LibraryType selectByPrimaryKey(Integer libtypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_type
     *
     * @mbg.generated Fri Mar 05 16:40:49 CST 2021
     */
    int updateByExampleSelective(@Param("record") LibraryType record, @Param("example") LibraryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_type
     *
     * @mbg.generated Fri Mar 05 16:40:49 CST 2021
     */
    int updateByExample(@Param("record") LibraryType record, @Param("example") LibraryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_type
     *
     * @mbg.generated Fri Mar 05 16:40:49 CST 2021
     */
    int updateByPrimaryKeySelective(LibraryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_type
     *
     * @mbg.generated Fri Mar 05 16:40:49 CST 2021
     */
    int updateByPrimaryKey(LibraryType record);
}