package com.lqs.sms.mapper;

import com.lqs.sms.entity.Phone;
import com.lqs.sms.entity.PhoneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PhoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbg.generated Fri Mar 05 19:01:31 CST 2021
     */
    long countByExample(PhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbg.generated Fri Mar 05 19:01:31 CST 2021
     */
    int deleteByExample(PhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbg.generated Fri Mar 05 19:01:31 CST 2021
     */
    int deleteByPrimaryKey(Integer phoneId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbg.generated Fri Mar 05 19:01:31 CST 2021
     */
    int insert(Phone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbg.generated Fri Mar 05 19:01:31 CST 2021
     */
    int insertSelective(Phone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbg.generated Fri Mar 05 19:01:31 CST 2021
     */
    List<Phone> selectByExample(PhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbg.generated Fri Mar 05 19:01:31 CST 2021
     */
    Phone selectByPrimaryKey(Integer phoneId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbg.generated Fri Mar 05 19:01:31 CST 2021
     */
    int updateByExampleSelective(@Param("record") Phone record, @Param("example") PhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbg.generated Fri Mar 05 19:01:31 CST 2021
     */
    int updateByExample(@Param("record") Phone record, @Param("example") PhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbg.generated Fri Mar 05 19:01:31 CST 2021
     */
    int updateByPrimaryKeySelective(Phone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbg.generated Fri Mar 05 19:01:31 CST 2021
     */
    int updateByPrimaryKey(Phone record);
}