package com.lqs.sms.mapper;

import com.lqs.sms.entity.SmsFrequency;
import com.lqs.sms.entity.SmsFrequencyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsFrequencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_frequency
     *
     * @mbg.generated Sat Mar 06 17:59:46 CST 2021
     */
    long countByExample(SmsFrequencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_frequency
     *
     * @mbg.generated Sat Mar 06 17:59:46 CST 2021
     */
    int deleteByExample(SmsFrequencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_frequency
     *
     * @mbg.generated Sat Mar 06 17:59:46 CST 2021
     */
    int deleteByPrimaryKey(Integer smsfrequencyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_frequency
     *
     * @mbg.generated Sat Mar 06 17:59:46 CST 2021
     */
    int insert(SmsFrequency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_frequency
     *
     * @mbg.generated Sat Mar 06 17:59:46 CST 2021
     */
    int insertSelective(SmsFrequency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_frequency
     *
     * @mbg.generated Sat Mar 06 17:59:46 CST 2021
     */
    List<SmsFrequency> selectByExample(SmsFrequencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_frequency
     *
     * @mbg.generated Sat Mar 06 17:59:46 CST 2021
     */
    SmsFrequency selectByPrimaryKey(Integer smsfrequencyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_frequency
     *
     * @mbg.generated Sat Mar 06 17:59:46 CST 2021
     */
    int updateByExampleSelective(@Param("record") SmsFrequency record, @Param("example") SmsFrequencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_frequency
     *
     * @mbg.generated Sat Mar 06 17:59:46 CST 2021
     */
    int updateByExample(@Param("record") SmsFrequency record, @Param("example") SmsFrequencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_frequency
     *
     * @mbg.generated Sat Mar 06 17:59:46 CST 2021
     */
    int updateByPrimaryKeySelective(SmsFrequency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_frequency
     *
     * @mbg.generated Sat Mar 06 17:59:46 CST 2021
     */
    int updateByPrimaryKey(SmsFrequency record);
}