package com.lqs.sms.mapper;

import com.lqs.sms.entity.SmsTaskPhone;
import com.lqs.sms.entity.SmsTaskPhoneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsTaskPhoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task_phone
     *
     * @mbg.generated Sun Mar 07 15:19:18 CST 2021
     */
    long countByExample(SmsTaskPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task_phone
     *
     * @mbg.generated Sun Mar 07 15:19:18 CST 2021
     */
    int deleteByExample(SmsTaskPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task_phone
     *
     * @mbg.generated Sun Mar 07 15:19:18 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task_phone
     *
     * @mbg.generated Sun Mar 07 15:19:18 CST 2021
     */
    int insert(SmsTaskPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task_phone
     *
     * @mbg.generated Sun Mar 07 15:19:18 CST 2021
     */
    int insertSelective(SmsTaskPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task_phone
     *
     * @mbg.generated Sun Mar 07 15:19:18 CST 2021
     */
    List<SmsTaskPhone> selectByExample(SmsTaskPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task_phone
     *
     * @mbg.generated Sun Mar 07 15:19:18 CST 2021
     */
    SmsTaskPhone selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task_phone
     *
     * @mbg.generated Sun Mar 07 15:19:18 CST 2021
     */
    int updateByExampleSelective(@Param("record") SmsTaskPhone record, @Param("example") SmsTaskPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task_phone
     *
     * @mbg.generated Sun Mar 07 15:19:18 CST 2021
     */
    int updateByExample(@Param("record") SmsTaskPhone record, @Param("example") SmsTaskPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task_phone
     *
     * @mbg.generated Sun Mar 07 15:19:18 CST 2021
     */
    int updateByPrimaryKeySelective(SmsTaskPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task_phone
     *
     * @mbg.generated Sun Mar 07 15:19:18 CST 2021
     */
    int updateByPrimaryKey(SmsTaskPhone record);
}