package com.lqs.sms.mapper;

import com.lqs.sms.entity.SmsTask;
import com.lqs.sms.entity.SmsTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

public interface SmsTaskMapper {
	
	/**
	 * 设置短信任务的停止时间为null
	 * @param smstaskId
	 * @return
	 */
	@Update("update sms_task set stop_time = null where smsTask_id=#{smstaskId}")
	int updateSmsTaskStopTimeNull(Integer smstaskId);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    long countByExample(SmsTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    int deleteByExample(SmsTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    int deleteByPrimaryKey(Integer smstaskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    int insert(SmsTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    int insertSelective(SmsTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    List<SmsTask> selectByExample(SmsTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    SmsTask selectByPrimaryKey(Integer smstaskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    int updateByExampleSelective(@Param("record") SmsTask record, @Param("example") SmsTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    int updateByExample(@Param("record") SmsTask record, @Param("example") SmsTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    int updateByPrimaryKeySelective(SmsTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    int updateByPrimaryKey(SmsTask record);
}