package com.lqs.sms.entity;

public class LibraryView {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column library_view.id
     *
     * @mbg.generated Fri Mar 05 16:41:07 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column library_view.lb_id
     *
     * @mbg.generated Fri Mar 05 16:41:07 CST 2021
     */
    private Integer lbId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column library_view.vi_id
     *
     * @mbg.generated Fri Mar 05 16:41:07 CST 2021
     */
    private Integer viId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column library_view.id
     *
     * @return the value of library_view.id
     *
     * @mbg.generated Fri Mar 05 16:41:07 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column library_view.id
     *
     * @param id the value for library_view.id
     *
     * @mbg.generated Fri Mar 05 16:41:07 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column library_view.lb_id
     *
     * @return the value of library_view.lb_id
     *
     * @mbg.generated Fri Mar 05 16:41:07 CST 2021
     */
    public Integer getLbId() {
        return lbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column library_view.lb_id
     *
     * @param lbId the value for library_view.lb_id
     *
     * @mbg.generated Fri Mar 05 16:41:07 CST 2021
     */
    public void setLbId(Integer lbId) {
        this.lbId = lbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column library_view.vi_id
     *
     * @return the value of library_view.vi_id
     *
     * @mbg.generated Fri Mar 05 16:41:07 CST 2021
     */
    public Integer getViId() {
        return viId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column library_view.vi_id
     *
     * @param viId the value for library_view.vi_id
     *
     * @mbg.generated Fri Mar 05 16:41:07 CST 2021
     */
    public void setViId(Integer viId) {
        this.viId = viId;
    }
}