package com.lqs.sms.entity;

public class Library {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column library.lb_id
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	private Integer lbId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column library.libType_id
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	private Integer libtypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column library.path
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	private String path;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column library.url
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column library.port
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	private String port;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column library.database_name
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	private String databaseName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column library.sid
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	private String sid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column library.user_name
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column library.password
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column library.description
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column library.lb_id
	 * @return  the value of library.lb_id
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	public Integer getLbId() {
		return lbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column library.lb_id
	 * @param lbId  the value for library.lb_id
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	public void setLbId(Integer lbId) {
		this.lbId = lbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column library.libType_id
	 * @return  the value of library.libType_id
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	public Integer getLibtypeId() {
		return libtypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column library.libType_id
	 * @param libtypeId  the value for library.libType_id
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	public void setLibtypeId(Integer libtypeId) {
		this.libtypeId = libtypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column library.path
	 * @return  the value of library.path
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column library.path
	 * @param path  the value for library.path
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	public void setPath(String path) {
		this.path = path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column library.url
	 * @return  the value of library.url
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column library.url
	 * @param url  the value for library.url
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column library.port
	 * @return  the value of library.port
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	public String getPort() {
		return port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column library.port
	 * @param port  the value for library.port
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	public void setPort(String port) {
		this.port = port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column library.database_name
	 * @return  the value of library.database_name
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	public String getDatabaseName() {
		return databaseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column library.database_name
	 * @param databaseName  the value for library.database_name
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	public void setDatabaseName(String databaseName) {
		this.databaseName = databaseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column library.sid
	 * @return  the value of library.sid
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	public String getSid() {
		return sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column library.sid
	 * @param sid  the value for library.sid
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	public void setSid(String sid) {
		this.sid = sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column library.user_name
	 * @return  the value of library.user_name
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column library.user_name
	 * @param userName  the value for library.user_name
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column library.password
	 * @return  the value of library.password
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column library.password
	 * @param password  the value for library.password
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column library.description
	 * @return  the value of library.description
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column library.description
	 * @param description  the value for library.description
	 * @mbg.generated  Mon Mar 08 19:34:27 CST 2021
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
     * 库类型名字
     */
    private String libTypeName;
    
    /**
     * 库视图名称字符串
     */
    private String libraryViewStr;

    public String getLibTypeName() {
		return libTypeName;
	}

	public void setLibTypeName(String libTypeName) {
		this.libTypeName = libTypeName;
	}

	public String getLibraryViewStr() {
		return libraryViewStr;
	}

	public void setLibraryViewStr(String libraryViewStr) {
		this.libraryViewStr = libraryViewStr;
	}

	public Library(Integer libtypeId, String path, String url, String port, String databaseName, String sid,
			String userName, String password, String description) {
		super();
		this.libtypeId = libtypeId;
		this.path = path;
		this.url = url;
		this.port = port;
		this.databaseName = databaseName;
		this.sid = sid;
		this.userName = userName;
		this.password = password;
		this.description = description;
	}
	

}