package com.lqs.sms.entity;

public class Library {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column library.lb_id
     *
     * @mbg.generated Fri Mar 05 18:22:17 CST 2021
     */
    private Integer lbId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column library.libType_id
     *
     * @mbg.generated Fri Mar 05 18:22:17 CST 2021
     */
    private Integer libtypeId;
    
    /**
     * 库类型名称
     */
    private String libTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column library.path
     *
     * @mbg.generated Fri Mar 05 18:22:17 CST 2021
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column library.url
     *
     * @mbg.generated Fri Mar 05 18:22:17 CST 2021
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column library.description
     *
     * @mbg.generated Fri Mar 05 18:22:17 CST 2021
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column library.lb_id
     *
     * @return the value of library.lb_id
     *
     * @mbg.generated Fri Mar 05 18:22:17 CST 2021
     */
    public Integer getLbId() {
        return lbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column library.lb_id
     *
     * @param lbId the value for library.lb_id
     *
     * @mbg.generated Fri Mar 05 18:22:17 CST 2021
     */
    public void setLbId(Integer lbId) {
        this.lbId = lbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column library.libType_id
     *
     * @return the value of library.libType_id
     *
     * @mbg.generated Fri Mar 05 18:22:17 CST 2021
     */
    public Integer getLibtypeId() {
        return libtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column library.libType_id
     *
     * @param libtypeId the value for library.libType_id
     *
     * @mbg.generated Fri Mar 05 18:22:17 CST 2021
     */
    public void setLibtypeId(Integer libtypeId) {
        this.libtypeId = libtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column library.path
     *
     * @return the value of library.path
     *
     * @mbg.generated Fri Mar 05 18:22:17 CST 2021
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column library.path
     *
     * @param path the value for library.path
     *
     * @mbg.generated Fri Mar 05 18:22:17 CST 2021
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column library.url
     *
     * @return the value of library.url
     *
     * @mbg.generated Fri Mar 05 18:22:17 CST 2021
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column library.url
     *
     * @param url the value for library.url
     *
     * @mbg.generated Fri Mar 05 18:22:17 CST 2021
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column library.description
     *
     * @return the value of library.description
     *
     * @mbg.generated Fri Mar 05 18:22:17 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column library.description
     *
     * @param description the value for library.description
     *
     * @mbg.generated Fri Mar 05 18:22:17 CST 2021
     */
    public void setDescription(String description) {
        this.description = description;
    }

	public String getLibTypeName() {
		return libTypeName;
	}

	public void setLibTypeName(String libTypeName) {
		this.libTypeName = libTypeName;
	}

	public Library(Integer libtypeId, String path, String url, String description) {
		super();
		this.libtypeId = libtypeId;
		this.path = path;
		this.url = url;
		this.description = description;
	}
    
    
}