package com.lqs.sms.entity;

public class LibraryType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column library_type.libType_id
     *
     * @mbg.generated Fri Mar 05 16:40:49 CST 2021
     */
    private Integer libtypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column library_type.name
     *
     * @mbg.generated Fri Mar 05 16:40:49 CST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column library_type.libType_id
     *
     * @return the value of library_type.libType_id
     *
     * @mbg.generated Fri Mar 05 16:40:49 CST 2021
     */
    public Integer getLibtypeId() {
        return libtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column library_type.libType_id
     *
     * @param libtypeId the value for library_type.libType_id
     *
     * @mbg.generated Fri Mar 05 16:40:49 CST 2021
     */
    public void setLibtypeId(Integer libtypeId) {
        this.libtypeId = libtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column library_type.name
     *
     * @return the value of library_type.name
     *
     * @mbg.generated Fri Mar 05 16:40:49 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column library_type.name
     *
     * @param name the value for library_type.name
     *
     * @mbg.generated Fri Mar 05 16:40:49 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }
}