package com.lqs.sms.entity;

public class Phone {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.phone_id
     *
     * @mbg.generated Fri Mar 05 19:01:31 CST 2021
     */
    private Integer phoneId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.name
     *
     * @mbg.generated Fri Mar 05 19:01:31 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.number
     *
     * @mbg.generated Fri Mar 05 19:01:31 CST 2021
     */
    private String number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.phone_id
     *
     * @return the value of phone.phone_id
     *
     * @mbg.generated Fri Mar 05 19:01:31 CST 2021
     */
    public Integer getPhoneId() {
        return phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.phone_id
     *
     * @param phoneId the value for phone.phone_id
     *
     * @mbg.generated Fri Mar 05 19:01:31 CST 2021
     */
    public void setPhoneId(Integer phoneId) {
        this.phoneId = phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.name
     *
     * @return the value of phone.name
     *
     * @mbg.generated Fri Mar 05 19:01:31 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.name
     *
     * @param name the value for phone.name
     *
     * @mbg.generated Fri Mar 05 19:01:31 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.number
     *
     * @return the value of phone.number
     *
     * @mbg.generated Fri Mar 05 19:01:31 CST 2021
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.number
     *
     * @param number the value for phone.number
     *
     * @mbg.generated Fri Mar 05 19:01:31 CST 2021
     */
    public void setNumber(String number) {
        this.number = number;
    }

	public Phone(String name, String number) {
		super();
		this.name = name;
		this.number = number;
	}
    
    
}
