package com.lqs.sms.entity;

public class SmsFrequency {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_frequency.smsFrequency_id
     *
     * @mbg.generated Sat Mar 06 17:59:46 CST 2021
     */
    private Integer smsfrequencyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_frequency.value
     *
     * @mbg.generated Sat Mar 06 17:59:46 CST 2021
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_frequency.description
     *
     * @mbg.generated Sat Mar 06 17:59:46 CST 2021
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_frequency.smsFrequency_id
     *
     * @return the value of sms_frequency.smsFrequency_id
     *
     * @mbg.generated Sat Mar 06 17:59:46 CST 2021
     */
    public Integer getSmsfrequencyId() {
        return smsfrequencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_frequency.smsFrequency_id
     *
     * @param smsfrequencyId the value for sms_frequency.smsFrequency_id
     *
     * @mbg.generated Sat Mar 06 17:59:46 CST 2021
     */
    public void setSmsfrequencyId(Integer smsfrequencyId) {
        this.smsfrequencyId = smsfrequencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_frequency.value
     *
     * @return the value of sms_frequency.value
     *
     * @mbg.generated Sat Mar 06 17:59:46 CST 2021
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_frequency.value
     *
     * @param value the value for sms_frequency.value
     *
     * @mbg.generated Sat Mar 06 17:59:46 CST 2021
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_frequency.description
     *
     * @return the value of sms_frequency.description
     *
     * @mbg.generated Sat Mar 06 17:59:46 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_frequency.description
     *
     * @param description the value for sms_frequency.description
     *
     * @mbg.generated Sat Mar 06 17:59:46 CST 2021
     */
    public void setDescription(String description) {
        this.description = description;
    }
}