package com.lqs.sms.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SmsTaskExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public SmsTaskExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSmstaskIdIsNull() {
            addCriterion("smsTask_id is null");
            return (Criteria) this;
        }

        public Criteria andSmstaskIdIsNotNull() {
            addCriterion("smsTask_id is not null");
            return (Criteria) this;
        }

        public Criteria andSmstaskIdEqualTo(Integer value) {
            addCriterion("smsTask_id =", value, "smstaskId");
            return (Criteria) this;
        }

        public Criteria andSmstaskIdNotEqualTo(Integer value) {
            addCriterion("smsTask_id <>", value, "smstaskId");
            return (Criteria) this;
        }

        public Criteria andSmstaskIdGreaterThan(Integer value) {
            addCriterion("smsTask_id >", value, "smstaskId");
            return (Criteria) this;
        }

        public Criteria andSmstaskIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("smsTask_id >=", value, "smstaskId");
            return (Criteria) this;
        }

        public Criteria andSmstaskIdLessThan(Integer value) {
            addCriterion("smsTask_id <", value, "smstaskId");
            return (Criteria) this;
        }

        public Criteria andSmstaskIdLessThanOrEqualTo(Integer value) {
            addCriterion("smsTask_id <=", value, "smstaskId");
            return (Criteria) this;
        }

        public Criteria andSmstaskIdIn(List<Integer> values) {
            addCriterion("smsTask_id in", values, "smstaskId");
            return (Criteria) this;
        }

        public Criteria andSmstaskIdNotIn(List<Integer> values) {
            addCriterion("smsTask_id not in", values, "smstaskId");
            return (Criteria) this;
        }

        public Criteria andSmstaskIdBetween(Integer value1, Integer value2) {
            addCriterion("smsTask_id between", value1, value2, "smstaskId");
            return (Criteria) this;
        }

        public Criteria andSmstaskIdNotBetween(Integer value1, Integer value2) {
            addCriterion("smsTask_id not between", value1, value2, "smstaskId");
            return (Criteria) this;
        }

        public Criteria andLbIdIsNull() {
            addCriterion("lb_id is null");
            return (Criteria) this;
        }

        public Criteria andLbIdIsNotNull() {
            addCriterion("lb_id is not null");
            return (Criteria) this;
        }

        public Criteria andLbIdEqualTo(Integer value) {
            addCriterion("lb_id =", value, "lbId");
            return (Criteria) this;
        }

        public Criteria andLbIdNotEqualTo(Integer value) {
            addCriterion("lb_id <>", value, "lbId");
            return (Criteria) this;
        }

        public Criteria andLbIdGreaterThan(Integer value) {
            addCriterion("lb_id >", value, "lbId");
            return (Criteria) this;
        }

        public Criteria andLbIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("lb_id >=", value, "lbId");
            return (Criteria) this;
        }

        public Criteria andLbIdLessThan(Integer value) {
            addCriterion("lb_id <", value, "lbId");
            return (Criteria) this;
        }

        public Criteria andLbIdLessThanOrEqualTo(Integer value) {
            addCriterion("lb_id <=", value, "lbId");
            return (Criteria) this;
        }

        public Criteria andLbIdIn(List<Integer> values) {
            addCriterion("lb_id in", values, "lbId");
            return (Criteria) this;
        }

        public Criteria andLbIdNotIn(List<Integer> values) {
            addCriterion("lb_id not in", values, "lbId");
            return (Criteria) this;
        }

        public Criteria andLbIdBetween(Integer value1, Integer value2) {
            addCriterion("lb_id between", value1, value2, "lbId");
            return (Criteria) this;
        }

        public Criteria andLbIdNotBetween(Integer value1, Integer value2) {
            addCriterion("lb_id not between", value1, value2, "lbId");
            return (Criteria) this;
        }

        public Criteria andViIdIsNull() {
            addCriterion("vi_id is null");
            return (Criteria) this;
        }

        public Criteria andViIdIsNotNull() {
            addCriterion("vi_id is not null");
            return (Criteria) this;
        }

        public Criteria andViIdEqualTo(Integer value) {
            addCriterion("vi_id =", value, "viId");
            return (Criteria) this;
        }

        public Criteria andViIdNotEqualTo(Integer value) {
            addCriterion("vi_id <>", value, "viId");
            return (Criteria) this;
        }

        public Criteria andViIdGreaterThan(Integer value) {
            addCriterion("vi_id >", value, "viId");
            return (Criteria) this;
        }

        public Criteria andViIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("vi_id >=", value, "viId");
            return (Criteria) this;
        }

        public Criteria andViIdLessThan(Integer value) {
            addCriterion("vi_id <", value, "viId");
            return (Criteria) this;
        }

        public Criteria andViIdLessThanOrEqualTo(Integer value) {
            addCriterion("vi_id <=", value, "viId");
            return (Criteria) this;
        }

        public Criteria andViIdIn(List<Integer> values) {
            addCriterion("vi_id in", values, "viId");
            return (Criteria) this;
        }

        public Criteria andViIdNotIn(List<Integer> values) {
            addCriterion("vi_id not in", values, "viId");
            return (Criteria) this;
        }

        public Criteria andViIdBetween(Integer value1, Integer value2) {
            addCriterion("vi_id between", value1, value2, "viId");
            return (Criteria) this;
        }

        public Criteria andViIdNotBetween(Integer value1, Integer value2) {
            addCriterion("vi_id not between", value1, value2, "viId");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andReceivePhoneStrIsNull() {
            addCriterion("receive_phone_str is null");
            return (Criteria) this;
        }

        public Criteria andReceivePhoneStrIsNotNull() {
            addCriterion("receive_phone_str is not null");
            return (Criteria) this;
        }

        public Criteria andReceivePhoneStrEqualTo(String value) {
            addCriterion("receive_phone_str =", value, "receivePhoneStr");
            return (Criteria) this;
        }

        public Criteria andReceivePhoneStrNotEqualTo(String value) {
            addCriterion("receive_phone_str <>", value, "receivePhoneStr");
            return (Criteria) this;
        }

        public Criteria andReceivePhoneStrGreaterThan(String value) {
            addCriterion("receive_phone_str >", value, "receivePhoneStr");
            return (Criteria) this;
        }

        public Criteria andReceivePhoneStrGreaterThanOrEqualTo(String value) {
            addCriterion("receive_phone_str >=", value, "receivePhoneStr");
            return (Criteria) this;
        }

        public Criteria andReceivePhoneStrLessThan(String value) {
            addCriterion("receive_phone_str <", value, "receivePhoneStr");
            return (Criteria) this;
        }

        public Criteria andReceivePhoneStrLessThanOrEqualTo(String value) {
            addCriterion("receive_phone_str <=", value, "receivePhoneStr");
            return (Criteria) this;
        }

        public Criteria andReceivePhoneStrLike(String value) {
            addCriterion("receive_phone_str like", value, "receivePhoneStr");
            return (Criteria) this;
        }

        public Criteria andReceivePhoneStrNotLike(String value) {
            addCriterion("receive_phone_str not like", value, "receivePhoneStr");
            return (Criteria) this;
        }

        public Criteria andReceivePhoneStrIn(List<String> values) {
            addCriterion("receive_phone_str in", values, "receivePhoneStr");
            return (Criteria) this;
        }

        public Criteria andReceivePhoneStrNotIn(List<String> values) {
            addCriterion("receive_phone_str not in", values, "receivePhoneStr");
            return (Criteria) this;
        }

        public Criteria andReceivePhoneStrBetween(String value1, String value2) {
            addCriterion("receive_phone_str between", value1, value2, "receivePhoneStr");
            return (Criteria) this;
        }

        public Criteria andReceivePhoneStrNotBetween(String value1, String value2) {
            addCriterion("receive_phone_str not between", value1, value2, "receivePhoneStr");
            return (Criteria) this;
        }

        public Criteria andSmsfrequencyIdIsNull() {
            addCriterion("smsFrequency_id is null");
            return (Criteria) this;
        }

        public Criteria andSmsfrequencyIdIsNotNull() {
            addCriterion("smsFrequency_id is not null");
            return (Criteria) this;
        }

        public Criteria andSmsfrequencyIdEqualTo(Integer value) {
            addCriterion("smsFrequency_id =", value, "smsfrequencyId");
            return (Criteria) this;
        }

        public Criteria andSmsfrequencyIdNotEqualTo(Integer value) {
            addCriterion("smsFrequency_id <>", value, "smsfrequencyId");
            return (Criteria) this;
        }

        public Criteria andSmsfrequencyIdGreaterThan(Integer value) {
            addCriterion("smsFrequency_id >", value, "smsfrequencyId");
            return (Criteria) this;
        }

        public Criteria andSmsfrequencyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("smsFrequency_id >=", value, "smsfrequencyId");
            return (Criteria) this;
        }

        public Criteria andSmsfrequencyIdLessThan(Integer value) {
            addCriterion("smsFrequency_id <", value, "smsfrequencyId");
            return (Criteria) this;
        }

        public Criteria andSmsfrequencyIdLessThanOrEqualTo(Integer value) {
            addCriterion("smsFrequency_id <=", value, "smsfrequencyId");
            return (Criteria) this;
        }

        public Criteria andSmsfrequencyIdIn(List<Integer> values) {
            addCriterion("smsFrequency_id in", values, "smsfrequencyId");
            return (Criteria) this;
        }

        public Criteria andSmsfrequencyIdNotIn(List<Integer> values) {
            addCriterion("smsFrequency_id not in", values, "smsfrequencyId");
            return (Criteria) this;
        }

        public Criteria andSmsfrequencyIdBetween(Integer value1, Integer value2) {
            addCriterion("smsFrequency_id between", value1, value2, "smsfrequencyId");
            return (Criteria) this;
        }

        public Criteria andSmsfrequencyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("smsFrequency_id not between", value1, value2, "smsfrequencyId");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIsNull() {
            addCriterion("begin_time is null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIsNotNull() {
            addCriterion("begin_time is not null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeEqualTo(Date value) {
            addCriterion("begin_time =", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotEqualTo(Date value) {
            addCriterion("begin_time <>", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeGreaterThan(Date value) {
            addCriterion("begin_time >", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("begin_time >=", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeLessThan(Date value) {
            addCriterion("begin_time <", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeLessThanOrEqualTo(Date value) {
            addCriterion("begin_time <=", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIn(List<Date> values) {
            addCriterion("begin_time in", values, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotIn(List<Date> values) {
            addCriterion("begin_time not in", values, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeBetween(Date value1, Date value2) {
            addCriterion("begin_time between", value1, value2, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotBetween(Date value1, Date value2) {
            addCriterion("begin_time not between", value1, value2, "beginTime");
            return (Criteria) this;
        }

        public Criteria andStopTimeIsNull() {
            addCriterion("stop_time is null");
            return (Criteria) this;
        }

        public Criteria andStopTimeIsNotNull() {
            addCriterion("stop_time is not null");
            return (Criteria) this;
        }

        public Criteria andStopTimeEqualTo(Date value) {
            addCriterion("stop_time =", value, "stopTime");
            return (Criteria) this;
        }

        public Criteria andStopTimeNotEqualTo(Date value) {
            addCriterion("stop_time <>", value, "stopTime");
            return (Criteria) this;
        }

        public Criteria andStopTimeGreaterThan(Date value) {
            addCriterion("stop_time >", value, "stopTime");
            return (Criteria) this;
        }

        public Criteria andStopTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("stop_time >=", value, "stopTime");
            return (Criteria) this;
        }

        public Criteria andStopTimeLessThan(Date value) {
            addCriterion("stop_time <", value, "stopTime");
            return (Criteria) this;
        }

        public Criteria andStopTimeLessThanOrEqualTo(Date value) {
            addCriterion("stop_time <=", value, "stopTime");
            return (Criteria) this;
        }

        public Criteria andStopTimeIn(List<Date> values) {
            addCriterion("stop_time in", values, "stopTime");
            return (Criteria) this;
        }

        public Criteria andStopTimeNotIn(List<Date> values) {
            addCriterion("stop_time not in", values, "stopTime");
            return (Criteria) this;
        }

        public Criteria andStopTimeBetween(Date value1, Date value2) {
            addCriterion("stop_time between", value1, value2, "stopTime");
            return (Criteria) this;
        }

        public Criteria andStopTimeNotBetween(Date value1, Date value2) {
            addCriterion("stop_time not between", value1, value2, "stopTime");
            return (Criteria) this;
        }

        public Criteria andSendCountIsNull() {
            addCriterion("send_count is null");
            return (Criteria) this;
        }

        public Criteria andSendCountIsNotNull() {
            addCriterion("send_count is not null");
            return (Criteria) this;
        }

        public Criteria andSendCountEqualTo(Integer value) {
            addCriterion("send_count =", value, "sendCount");
            return (Criteria) this;
        }

        public Criteria andSendCountNotEqualTo(Integer value) {
            addCriterion("send_count <>", value, "sendCount");
            return (Criteria) this;
        }

        public Criteria andSendCountGreaterThan(Integer value) {
            addCriterion("send_count >", value, "sendCount");
            return (Criteria) this;
        }

        public Criteria andSendCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("send_count >=", value, "sendCount");
            return (Criteria) this;
        }

        public Criteria andSendCountLessThan(Integer value) {
            addCriterion("send_count <", value, "sendCount");
            return (Criteria) this;
        }

        public Criteria andSendCountLessThanOrEqualTo(Integer value) {
            addCriterion("send_count <=", value, "sendCount");
            return (Criteria) this;
        }

        public Criteria andSendCountIn(List<Integer> values) {
            addCriterion("send_count in", values, "sendCount");
            return (Criteria) this;
        }

        public Criteria andSendCountNotIn(List<Integer> values) {
            addCriterion("send_count not in", values, "sendCount");
            return (Criteria) this;
        }

        public Criteria andSendCountBetween(Integer value1, Integer value2) {
            addCriterion("send_count between", value1, value2, "sendCount");
            return (Criteria) this;
        }

        public Criteria andSendCountNotBetween(Integer value1, Integer value2) {
            addCriterion("send_count not between", value1, value2, "sendCount");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sms_task
     *
     * @mbg.generated do_not_delete_during_merge Sat Mar 06 18:14:19 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sms_task
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}