package com.lqs.sms.entity;

import java.util.Date;

public class SmsTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_task.smsTask_id
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    private Integer smstaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_task.lb_id
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    private Integer lbId;
    
    /**
     * 库路径
     */
    private String libraryPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_task.vi_id
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    private Integer viId;
    
    /**
     * 视图名称
     */
    private String viewName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_task.content
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_task.receive_phone_str
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    private String receivePhoneStr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_task.smsFrequency_id
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    private Integer smsfrequencyId;
    
    /**
     * 短信任务频次描述
     */
    private String smsfrequencyDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_task.begin_time
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    private Date beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_task.stop_time
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    private Date stopTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_task.send_count
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    private Integer sendCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_task.status
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    private Integer status;
    
    /**
     * 状态名字
     * 0：已关闭
     * 1：已开启
     */
    private String statusDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_task.smsTask_id
     *
     * @return the value of sms_task.smsTask_id
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public Integer getSmstaskId() {
        return smstaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_task.smsTask_id
     *
     * @param smstaskId the value for sms_task.smsTask_id
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public void setSmstaskId(Integer smstaskId) {
        this.smstaskId = smstaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_task.lb_id
     *
     * @return the value of sms_task.lb_id
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public Integer getLbId() {
        return lbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_task.lb_id
     *
     * @param lbId the value for sms_task.lb_id
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public void setLbId(Integer lbId) {
        this.lbId = lbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_task.vi_id
     *
     * @return the value of sms_task.vi_id
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public Integer getViId() {
        return viId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_task.vi_id
     *
     * @param viId the value for sms_task.vi_id
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public void setViId(Integer viId) {
        this.viId = viId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_task.content
     *
     * @return the value of sms_task.content
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_task.content
     *
     * @param content the value for sms_task.content
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_task.receive_phone_str
     *
     * @return the value of sms_task.receive_phone_str
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public String getReceivePhoneStr() {
        return receivePhoneStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_task.receive_phone_str
     *
     * @param receivePhoneStr the value for sms_task.receive_phone_str
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public void setReceivePhoneStr(String receivePhoneStr) {
        this.receivePhoneStr = receivePhoneStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_task.smsFrequency_id
     *
     * @return the value of sms_task.smsFrequency_id
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public Integer getSmsfrequencyId() {
        return smsfrequencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_task.smsFrequency_id
     *
     * @param smsfrequencyId the value for sms_task.smsFrequency_id
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public void setSmsfrequencyId(Integer smsfrequencyId) {
        this.smsfrequencyId = smsfrequencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_task.begin_time
     *
     * @return the value of sms_task.begin_time
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_task.begin_time
     *
     * @param beginTime the value for sms_task.begin_time
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_task.stop_time
     *
     * @return the value of sms_task.stop_time
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public Date getStopTime() {
        return stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_task.stop_time
     *
     * @param stopTime the value for sms_task.stop_time
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public void setStopTime(Date stopTime) {
        this.stopTime = stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_task.send_count
     *
     * @return the value of sms_task.send_count
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public Integer getSendCount() {
        return sendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_task.send_count
     *
     * @param sendCount the value for sms_task.send_count
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public void setSendCount(Integer sendCount) {
        this.sendCount = sendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_task.status
     *
     * @return the value of sms_task.status
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_task.status
     *
     * @param status the value for sms_task.status
     *
     * @mbg.generated Sat Mar 06 18:14:19 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public String getLibraryPath() {
		return libraryPath;
	}

	public void setLibraryPath(String libraryPath) {
		this.libraryPath = libraryPath;
	}
	
	public String getViewName() {
		return viewName;
	}

	public void setViewName(String viewName) {
		this.viewName = viewName;
	}

	public String getSmsfrequencyDescription() {
		return smsfrequencyDescription;
	}

	public void setSmsfrequencyDescription(String smsfrequencyDescription) {
		this.smsfrequencyDescription = smsfrequencyDescription;
	}

	public String getStatusDescription() {
		return statusDescription;
	}

	public void setStatusDescription(String statusDescription) {
		this.statusDescription = statusDescription;
	}
    
	
}