package com.lqs.sms.entity;

public class SmsTaskPhone {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_task_phone.id
     *
     * @mbg.generated Sun Mar 07 15:19:18 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_task_phone.smsTask_id
     *
     * @mbg.generated Sun Mar 07 15:19:18 CST 2021
     */
    private Integer smstaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_task_phone.phone_id
     *
     * @mbg.generated Sun Mar 07 15:19:18 CST 2021
     */
    private Integer phoneId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_task_phone.id
     *
     * @return the value of sms_task_phone.id
     *
     * @mbg.generated Sun Mar 07 15:19:18 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_task_phone.id
     *
     * @param id the value for sms_task_phone.id
     *
     * @mbg.generated Sun Mar 07 15:19:18 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_task_phone.smsTask_id
     *
     * @return the value of sms_task_phone.smsTask_id
     *
     * @mbg.generated Sun Mar 07 15:19:18 CST 2021
     */
    public Integer getSmstaskId() {
        return smstaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_task_phone.smsTask_id
     *
     * @param smstaskId the value for sms_task_phone.smsTask_id
     *
     * @mbg.generated Sun Mar 07 15:19:18 CST 2021
     */
    public void setSmstaskId(Integer smstaskId) {
        this.smstaskId = smstaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_task_phone.phone_id
     *
     * @return the value of sms_task_phone.phone_id
     *
     * @mbg.generated Sun Mar 07 15:19:18 CST 2021
     */
    public Integer getPhoneId() {
        return phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_task_phone.phone_id
     *
     * @param phoneId the value for sms_task_phone.phone_id
     *
     * @mbg.generated Sun Mar 07 15:19:18 CST 2021
     */
    public void setPhoneId(Integer phoneId) {
        this.phoneId = phoneId;
    }
}