package com.lqs.sms.entity;

import java.util.ArrayList;
import java.util.List;

public class ViewExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table view
	 * @mbg.generated  Mon Mar 08 23:46:11 CST 2021
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table view
	 * @mbg.generated  Mon Mar 08 23:46:11 CST 2021
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table view
	 * @mbg.generated  Mon Mar 08 23:46:11 CST 2021
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table view
	 * @mbg.generated  Mon Mar 08 23:46:11 CST 2021
	 */
	public ViewExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table view
	 * @mbg.generated  Mon Mar 08 23:46:11 CST 2021
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table view
	 * @mbg.generated  Mon Mar 08 23:46:11 CST 2021
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table view
	 * @mbg.generated  Mon Mar 08 23:46:11 CST 2021
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table view
	 * @mbg.generated  Mon Mar 08 23:46:11 CST 2021
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table view
	 * @mbg.generated  Mon Mar 08 23:46:11 CST 2021
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table view
	 * @mbg.generated  Mon Mar 08 23:46:11 CST 2021
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table view
	 * @mbg.generated  Mon Mar 08 23:46:11 CST 2021
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table view
	 * @mbg.generated  Mon Mar 08 23:46:11 CST 2021
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table view
	 * @mbg.generated  Mon Mar 08 23:46:11 CST 2021
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table view
	 * @mbg.generated  Mon Mar 08 23:46:11 CST 2021
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table view
	 * @mbg.generated  Mon Mar 08 23:46:11 CST 2021
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andViIdIsNull() {
			addCriterion("vi_id is null");
			return (Criteria) this;
		}

		public Criteria andViIdIsNotNull() {
			addCriterion("vi_id is not null");
			return (Criteria) this;
		}

		public Criteria andViIdEqualTo(Integer value) {
			addCriterion("vi_id =", value, "viId");
			return (Criteria) this;
		}

		public Criteria andViIdNotEqualTo(Integer value) {
			addCriterion("vi_id <>", value, "viId");
			return (Criteria) this;
		}

		public Criteria andViIdGreaterThan(Integer value) {
			addCriterion("vi_id >", value, "viId");
			return (Criteria) this;
		}

		public Criteria andViIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("vi_id >=", value, "viId");
			return (Criteria) this;
		}

		public Criteria andViIdLessThan(Integer value) {
			addCriterion("vi_id <", value, "viId");
			return (Criteria) this;
		}

		public Criteria andViIdLessThanOrEqualTo(Integer value) {
			addCriterion("vi_id <=", value, "viId");
			return (Criteria) this;
		}

		public Criteria andViIdIn(List<Integer> values) {
			addCriterion("vi_id in", values, "viId");
			return (Criteria) this;
		}

		public Criteria andViIdNotIn(List<Integer> values) {
			addCriterion("vi_id not in", values, "viId");
			return (Criteria) this;
		}

		public Criteria andViIdBetween(Integer value1, Integer value2) {
			addCriterion("vi_id between", value1, value2, "viId");
			return (Criteria) this;
		}

		public Criteria andViIdNotBetween(Integer value1, Integer value2) {
			addCriterion("vi_id not between", value1, value2, "viId");
			return (Criteria) this;
		}

		public Criteria andLbIdIsNull() {
			addCriterion("lb_id is null");
			return (Criteria) this;
		}

		public Criteria andLbIdIsNotNull() {
			addCriterion("lb_id is not null");
			return (Criteria) this;
		}

		public Criteria andLbIdEqualTo(Integer value) {
			addCriterion("lb_id =", value, "lbId");
			return (Criteria) this;
		}

		public Criteria andLbIdNotEqualTo(Integer value) {
			addCriterion("lb_id <>", value, "lbId");
			return (Criteria) this;
		}

		public Criteria andLbIdGreaterThan(Integer value) {
			addCriterion("lb_id >", value, "lbId");
			return (Criteria) this;
		}

		public Criteria andLbIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("lb_id >=", value, "lbId");
			return (Criteria) this;
		}

		public Criteria andLbIdLessThan(Integer value) {
			addCriterion("lb_id <", value, "lbId");
			return (Criteria) this;
		}

		public Criteria andLbIdLessThanOrEqualTo(Integer value) {
			addCriterion("lb_id <=", value, "lbId");
			return (Criteria) this;
		}

		public Criteria andLbIdIn(List<Integer> values) {
			addCriterion("lb_id in", values, "lbId");
			return (Criteria) this;
		}

		public Criteria andLbIdNotIn(List<Integer> values) {
			addCriterion("lb_id not in", values, "lbId");
			return (Criteria) this;
		}

		public Criteria andLbIdBetween(Integer value1, Integer value2) {
			addCriterion("lb_id between", value1, value2, "lbId");
			return (Criteria) this;
		}

		public Criteria andLbIdNotBetween(Integer value1, Integer value2) {
			addCriterion("lb_id not between", value1, value2, "lbId");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("description is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("description is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("description =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("description <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("description >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("description >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("description <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("description <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("description like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("description not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("description in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("description not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("description between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("description not between", value1, value2, "description");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table view
	 * @mbg.generated  Mon Mar 08 23:46:11 CST 2021
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table view
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 05 18:31:43 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}